### ISSUE TITLE
Dunegon balance

### ISSUE THREAD

**Issue by Shadopaku** [Weebs-Kingdom/Yuki-Sora#77] opened 2021-01-24 14:44 UTC
Add Level option to learnset (monster). (example: monster "A" gets artack "A" at level 10 and monster "B" gets attack "A" at level 15)

**Comment by MindCollaps** [comment] 2021-02-08 06:35
Duplicate of [this issue](https://github.com/Weebs-Kingdom/Yuki-Sora/issues/46)

**Closed by MindCollaps** 2021-02-08 06:35 UTC
Labels: duplicate, enhancement
